package main

var positions = []string{
	"TOP",
	"JGL",
	"MID",
	"BOT",
	"SUP",
}

var roles = []string{
	"Artillery",
	"Assassin",
	"Battlemage",
	"Burst",
	"Catcher",
	"Diver",
	"Enchanter",
	"Juggernaut",
	"Marksman",
	"Skirmisher",
	"Specialist",
	"Vanguard",
	"Warden",
}

var champStr = []string{
	"Aatrox Juggernaut Mid Top Jgl",
	"Ahri Burst Mid",
	"Akali Assassin Mid Top",
	"Alistar Vanguard Sup",
	"Amumu Vanguard Jgl",
	"Anivia Battlemage Mid",
	"Annie Burst Mid Sup",
	"Ashe Marksman Bot Sup",
	"Aurelion_Sol Battlemage Mid Jgl",
	"Azir Specialist Mid",
	"Bard Catcher Sup Jgl",
	"Blitzcrank Catcher Sup",
	"Brand Burst Mid Sup",
	"Braum Warden Sup",
	"Caitlyn Marksman Bot",
	"Camille Diver Top Jgl Mid Sup",
	"Cassiopeia Battlemage Top Mid Bot",
	"Cho'Gath Specialist Top Jgl Mid",
	"Corki Marksman Mid Bot",
	"Darius Juggernaut Top",
	"Diana Assassin Diver Top Mid Jgl",
	"Dr.Mundo Juggernaut Top Jgl",
	"Draven Marksman Bot Mid",
	"Ekko Assassin Top Jgl Mid",
	"Elise Diver Top Jgl Mid",
	"Evelynn Assassin Jgl",
	"Ezreal Marksman Mid Bot Jgl",
	"Fiddlesticks Specialist Jgl Sup",
	"Fiora Skirmisher Top",
	"Fizz Assassin Top Mid Jgl",
	"Galio Warden Top Mid Sup",
	"Gangplank Specialist Top Mid",
	"Garen Juggernaut Top",
	"Gnar Specialist Top",
	"Gragas Vanguard Top Jgl Mid Sup",
	"Graves Specialist Top Jgl",
	"Hecarim Diver Top Jgl",
	"Heimerdinger Specialist Top Mid Bot",
	"Illaoi Juggernaut Top Sup",
	"Irelia Diver Top Mid",
	"Ivern Catcher Jgl Sup",
	"Janna Enchanter Sup",
	"JarvanIV Diver Top Jgl Sup",
	"Jax Skrimisher Top Jgl",
	"Jayce Artillery Top Mid Bot",
	"Jhin Marksman Catcher Bot",
	"Jinx Marksman Bot",
	"Kai'Sa Marksman Jgl Bot",
	"Kalista Marksman Bot",
	"Karma Burst Enchanter Skirmisher Top Mid Bot Sup",
	"Karthus Battlemage Jgl Mid Sup",
	"Kassadin Assassin Mid",
	"Katarina Assassin Mid",
	"Kayle Specialist Top Mid",
	"Kayn Skirmisher Assassin Jgl Mid",
	"Kennen Specialist Top Mid Bot Sup",
	"Kha'Zix Assassin Jgl",
	"Kindred Marksman Jgl",
	"Kled Diver Top",
	"Kog'Maw Marksman Artillery Bot Mid",
	"LeBlanc Burst Assassin Mid",
	"Lee_Sin Diver Jgl",
	"Leona Vanguard Bot",
	"Lissandra Burst Mid Top Bot",
	"Lucian Marksman Top Mid Bot",
	"Lulu Enchanter Top Mid Sup",
	"Lux Burst Artillery Mid Sup",
	"Malphite Vanguard Top Mid Sup",
	"Malzahar Battlemage Mid Sup",
	"Maokai Vanguard Top Jgl Sup",
	"Master_Yi Skirmisher Top Jgl",
	"Miss_Fortune Marksman Bot Sup",
	"Mordekaiser Juggernaut Top Mid",
	"Morgana Catcher Mid Sup",
	"Nami Enchanter Sup",
	"Nasus Juggernaut Top Jgl",
	"Nautilus Vanguard Jgl Sup",
	"Neeko Burst Catcher Mid Top",
	"Nidalee Specialist Jgl",
	"Nocturne Assassin Skirmisher Jgl",
	"Nunu Vanguard Jgl Sup",
	"Olaf Diver Top Jgl",
	"Orianna Burst Mid Bot",
	"Ornn Vanguard Top",
	"Pantheon Diver Top Jgl",
	"Poppy Warden Top Jgl",
	"Pyke Assassin Top Mid Sup",
	"Qiyana Assassin Mid Jgl",
	"Quinn Assassin Specialist Top Mid Jgl Bot",
	"Rakan Catcher Sup",
	"Rammus Vanguard Top Jgl",
	"Rek'Sai Diver Jgl",
	"Renekton Diver Top Mid",
	"Rengar Assasin Diver Top Jgl",
	"Riven Skirmisher Top Mid",
	"Rumble Battlemage Top Mid Jgl",
	"Ryze Battlemage Top Mid Bot",
	"Sejuani Vanguard Jgl",
	"Shaco Assassin Top Jgl",
	"Shen Warden Top",
	"Shyvana Juggernaut Jgl",
	"Singed Specialist Top",
	"Sion Vanguard Top Mid",
	"Sivir Marksman Bot",
	"Skarner Diver Jgl",
	"Sona Enchanter Bot Sup",
	"Soraka Enchanter Sup",
	"Swain Battlemage Top Mid",
	"Sylas Burst Skirmisher Top Jgl Mid",
	"Syndra Burst Mid Bot",
	"Tahm_Kench Warden Sup Top",
	"Taliyah Battlemage Mid Jgl",
	"Talon Assassin Mid",
	"Taric Enchanter Warden Sup",
	"Teemo Specialist Top",
	"Thresh Catcher Sup",
	"Tristana Marksman Bot Mid",
	"Trundle Juggernaut Top Jgl Sup",
	"Tryndamere Skirmisher Top",
	"Twisted_Fate Battlemage Catcher Mid",
	"Twitch Marksman Jgl Bot",
	"Udyr Juggernaut Jgl",
	"Urgot Juggernaut Top Mid",
	"Varus Marksman Artillery Bot",
	"Vayne Marksman Bot Top",
	"Veigar Burst Mid Sup",
	"Vel'Koz Aritllery Mid Sup",
	"Vi Diver Jgl",
	"Viktor Battlemage Top Mid Bot",
	"Vladimir Battlemage Top Mid",
	"Volibear Juggernaut Top Jgl Sup",
	"Warwick Diver Jungle",
	"Wukong Diver Top Jgl",
	"Xayah Marksman Bot",
	"Xerath Artillery Mid Bot Sup",
	"Xin_Zhao Diver Jgl",
	"Yasuo Skirmisher Mid Top",
	"Yorick Juggernaut Top",
	"Yuumi Enchanter Sup",
	"Zac Vanguard Jgl",
	"Zed Assassin Mid",
	"Ziggs Artillery Mid Bot",
	"Zilean Specialist Mid Sup",
	"Zoe Burst Mid Bot",
	"Zyra Catcher Sup",
}

var champions = toChamps()

func toChamps() []champion {
	arr := make([]champion, len(champStr))
	for i, v := range champStr {
		arr[i] = newChamp(v)
	}
	return arr
}
